"""auto update

Revision ID: 4143fb5528b1
Revises: d9d14cb3ad57
Create Date: 2026-08-16 03:52:35.111483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4143fb5528b1'
down_revision: Union[str, Sequence[str], None] = 'd9d14cb3ad57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_maps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_maps_id'), 'shared_maps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_maps_id'), table_name='shared_maps')
    op.drop_table('shared_maps')
    # ### end Alembic commands ###