"""auto update

Revision ID: d7c6afedb5eb
Revises: 51c73e7440ea
Create Date: 2026-08-14 11:28:34.466451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c6afedb5eb'
down_revision: Union[str, Sequence[str], None] = '51c73e7440ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('feedback_type', sa.String(length=20), server_default='normal', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'feedback_type')
    # ### end Alembic commands ###